ci: Factorize `skore.yml` and `skore-remote-project.yml` in `pytest.yml`

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -1,4 +1,4 @@
-name: skore
+name: pytest
 
 on:
   pull_request:
@@ -19,30 +19,51 @@ defaults:
     shell: "bash"
 
 jobs:
-  skore-changes:
+  pytest-changes:
     runs-on: ubuntu-latest
     outputs:
-      changes: ${{ steps.filter.outputs.skore }}
+      all-packages: ${{ steps.filter-keys.outputs.keys }}
+      modified-packages: ${{ steps.filter.outputs.changes }}
     permissions:
       pull-requests: read
     steps:
       - name: Checkout code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Define if at least one file has changed
+      - id: filter
+        name: Define if at least one file has changed
         uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
-        id: filter
         with:
           filters: |
             skore:
-              - '.github/workflows/skore.yml'
+              - '.github/workflows/pytest.yml'
               - 'ci/requirements/skore/**'
               - 'skore/**'
+            skore-remote-project:
+              - '.github/workflows/pytest.yml'
+              - 'ci/requirements/skore-remote-project/**'
+              - 'skore-remote-project/**'
 
-  skore-lockfiles:
-    runs-on: "ubuntu-latest"
-    needs: [skore-changes]
-    if: ${{ (contains(fromJSON('["pull_request", "merge_group"]'), github.event_name)) && (needs.skore-changes.outputs.changes == 'true') }}
+      - id: filter-keys
+        run: |
+          # {
+          #     "<package>": "boolean",
+          #     "<package>_count": "int",
+          #     "changes": list
+          # }
+          keys=$(echo "${FILTER_OUTPUTS}" | jq -c 'to_entries | map(select(.value == "true" or .value == "false")) | from_entries | keys')
+          echo "keys=${keys}" >> $GITHUB_OUTPUT
+        env:
+          FILTER_OUTPUTS: ${{ toJSON(steps.filter.outputs) }}
+
+  pytest-lockfiles:
+    runs-on: ubuntu-latest
+    needs: [pytest-changes]
+    if: ${{ (contains(fromJSON('["pull_request", "merge_group"]'), github.event_name)) && (needs.pytest-changes.outputs.modified-packages != '[]') }}
+    strategy:
+      fail-fast: false
+      matrix:
+        package: ${{ fromJSON(needs.pytest-changes.outputs.modified-packages) }}
     permissions:
       contents: read
     steps:
@@ -72,28 +93,37 @@ jobs:
           changes=$(git diff --name-only HEAD^1 HEAD)
 
           if
-            (echo "${changes}" | grep -qE "skore/pyproject.toml") &&
-            (echo "${changes}" | (! grep -qE "ci/requirements/skore/.*/test-requirements.txt"))
+            (echo "${changes}" | grep -qE "${{ matrix.package }}/pyproject.toml") &&
+            (echo "${changes}" | (! grep -qE "ci/requirements/${{ matrix.package }}/.*/test-requirements.txt"))
           then
               curl -LsSf https://astral.sh/uv/0.6.16/install.sh | sh
-              bash ci/pip-compile.sh skore
+              bash ci/pip-compile.sh ${{ matrix.package }}
 
-              if (git diff --name-only | grep -qE "ci/requirements/skore/.*/test-requirements.txt"); then
-                  echo '::error title=skore-lockfiles::Lockfiles obsolete, please execute `$ bash ci/pip-compile.sh skore`'
+              if (git diff --name-only | grep -qE "ci/requirements/${{ matrix.package }}/.*/test-requirements.txt"); then
+                  echo '::error title=${{ matrix.package }}-lockfiles::Lockfiles obsolete, please execute `$ bash ci/pip-compile.sh ${{ matrix.package }}`'
                   exit 1
              fi
           fi
 
-  skore-test:
-    needs: [skore-changes]
-    if: ${{ (github.event_name == 'push') || (needs.skore-changes.outputs.changes == 'true') }}
+  pytest-test:
+    needs: [pytest-changes]
+    if: ${{ (github.event_name == 'push') || (needs.pytest-changes.outputs.modified-packages != '[]') }}
     strategy:
       fail-fast: false
       matrix:
+        package: ${{ (github.event_name == 'push') && fromJSON(needs.pytest-changes.outputs.all-packages) || fromJSON(needs.pytest-changes.outputs.modified-packages) }}
         os: ["ubuntu-latest", "windows-latest"]
         python: ["3.9", "3.10", "3.11", "3.12"]
-        scikit-learn: ["1.6"]
         include:
+          - python: "3.9"
+            scikit-learn: "1.6"
+          - python: "3.10"
+            scikit-learn: "1.6"
+          - python: "3.11"
+            scikit-learn: "1.6"
+          - os: "windows-latest"
+            python: "3.12"
+            scikit-learn: "1.6"
           - os: "ubuntu-latest"
             python: "3.12"
             scikit-learn: "1.4"
@@ -123,15 +153,15 @@ jobs:
         uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
         id: cache-python-venv
         with:
-          path: 'skore/venv'
+          path: ${{ matrix.package }}/venv
           key: >-
             python-venv
             -${{ matrix.os }}
             -${{ steps.setup-python.outputs.python-version }}
-            -${{ hashFiles(format('ci/requirements/skore/python-{0}/scikit-learn-{1}/test-requirements.txt', matrix.python, matrix.scikit-learn)) }}
+            -${{ hashFiles(format('ci/requirements/{0}/python-{1}/scikit-learn-{2}/test-requirements.txt', matrix.package, matrix.python, matrix.scikit-learn)) }}
 
       - name: Setup python-venv
-        working-directory: "skore/"
+        working-directory: ${{ matrix.package }}/
         run: |
           set -eu
 
@@ -140,15 +170,15 @@ jobs:
 
           # Activate venv for each step depending on the OS
           if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
-              echo "${GITHUB_WORKSPACE}/skore/venv/bin" >> ${GITHUB_PATH}
-              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}/skore/venv" >> ${GITHUB_ENV}
+              echo "${GITHUB_WORKSPACE}/${{ matrix.package }}/venv/bin" >> ${GITHUB_PATH}
+              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}/${{ matrix.package }}/venv" >> ${GITHUB_ENV}
           else
-              echo "${GITHUB_WORKSPACE}\\skore\\venv\\Scripts" >> ${GITHUB_PATH}
-              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}\\skore\\venv" >> ${GITHUB_ENV}
+              echo "${GITHUB_WORKSPACE}\\${{ matrix.package }}\\venv\\Scripts" >> ${GITHUB_PATH}
+              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}\\${{ matrix.package }}\\venv" >> ${GITHUB_ENV}
           fi
 
       - name: Install dependencies in python-venv
-        working-directory: ${{ format('ci/requirements/skore/python-{0}/scikit-learn-{1}', matrix.python, matrix.scikit-learn) }}
+        working-directory: ${{ format('ci/requirements/{0}/python-{1}/scikit-learn-{2}', matrix.package, matrix.python, matrix.scikit-learn) }}
         if: steps.cache-python-venv.outputs.cache-hit != 'true'
         run: |
           python -m pip install --upgrade pip build
@@ -158,31 +188,27 @@ jobs:
         uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
         if: steps.cache-python-venv.outputs.cache-hit != 'true'
         with:
-          path: 'skore/venv'
+          path: ${{ matrix.package }}/venv
           key: ${{ steps.cache-python-venv.outputs.cache-primary-key }}
 
       - name: Build
-        working-directory: skore/
+        working-directory: ${{ matrix.package }}/
         run: python -m build
 
       - name: Install
-        working-directory: skore/dist/
+        working-directory: ${{ matrix.package }}/dist/
         run: wheel=(*.whl); python -m pip install --force-reinstall --no-deps "${wheel}"
-
-      - name: Show dependencies versions
-        working-directory: skore/
-        run: python -c 'import skore; skore.show_versions()'
 
       - name: Test without coverage
         if: ${{ ! matrix.coverage }}
         timeout-minutes: 10
-        working-directory: skore/
+        working-directory: ${{ matrix.package }}/
         run: python -m pytest -n auto src/ tests/ --no-cov
 
       - name: Test with coverage
         if: ${{ matrix.coverage }}
         timeout-minutes: 10
-        working-directory: skore/
+        working-directory: ${{ matrix.package }}/
         run: |
           mkdir coverage
           python -m pytest -n auto src/ tests/ --junitxml=coverage/pytest.xml --cov-config=pyproject.toml --cov-report=xml:coverage/pytest-coverage.xml --cov
@@ -191,16 +217,16 @@ jobs:
         if: ${{ matrix.coverage && (github.event_name == 'pull_request') }}
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
         with:
-          name: skore-coverage
-          path: skore/coverage/
+          name: ${{ matrix.package }}-coverage
+          path: ${{ matrix.package }}/coverage/
 
-  skore:
+  pytest:
     needs:
-      - skore-changes
-      - skore-lockfiles
-      - skore-test
+      - pytest-changes
+      - pytest-lockfiles
+      - pytest-test
     if: ${{ always() }}
-    runs-on: Ubuntu-latest
+    runs-on: ubuntu-latest
     steps:
       - shell: bash
         run: |
