FIIIIIIIIIIIIIIIIIIIIIIIIX

diff --git a/.github/workflows/skore.yml b/.github/workflows/skore.yml
--- a/.github/workflows/skore.yml
+++ b/.github/workflows/skore.yml
@@ -19,87 +19,81 @@ defaults:
     shell: "bash"
 
 jobs:
-  skore-changes:
-    runs-on: ubuntu-latest
-    outputs:
-      changes: ${{ steps.filter.outputs.skore }}
-    permissions:
-      pull-requests: read
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  # skore-changes:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     changes: ${{ steps.filter.outputs.skore }}
+  #   permissions:
+  #     pull-requests: read
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Define if at least one file has changed
-        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
-        id: filter
-        with:
-          filters: |
-            skore:
-              - '.github/workflows/skore.yml'
-              - 'ci/requirements/skore/**'
-              - 'skore/**'
+  #     - name: Define if at least one file has changed
+  #       uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
+  #       id: filter
+  #       with:
+  #         filters: |
+  #           skore:
+  #             - '.github/workflows/skore.yml'
+  #             - 'ci/requirements/skore/**'
+  #             - 'skore/**'
 
-  skore-lockfiles:
-    runs-on: "ubuntu-latest"
-    needs: [skore-changes]
-    if: ${{ (contains(fromJSON('["pull_request", "merge_group"]'), github.event_name)) && (needs.skore-changes.outputs.changes == 'true') }}
-    permissions:
-      contents: read
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          fetch-depth: 2
+  # skore-lockfiles:
+  #   runs-on: "ubuntu-latest"
+  #   needs: [skore-changes]
+  #   if: ${{ (contains(fromJSON('["pull_request", "merge_group"]'), github.event_name)) && (needs.skore-changes.outputs.changes == 'true') }}
+  #   permissions:
+  #     contents: read
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  #       with:
+  #         fetch-depth: 2
 
-      - name: Check lockfiles are not obsolete
-        run: |
-          set -eu
+  #     - name: Check lockfiles are not obsolete
+  #       run: |
+  #         set -eu
 
-          # Check if `pyproject.toml` has changed in this pull-request
-          # ├── False
-          # │   └── Exit 0
-          # └── True
-          #     └── Check if lockfiles have changed in this pull-request
-          #         ├── True
-          #         │   └── Exit 0
-          #         └── False
-          #             └── Recompile lockfiles and check if they have to change
-          #                 ├── False
-          #                 │   └── Exit 0
-          #                 └── True
-          #                     └── Exit 1
+  #         # Check if `pyproject.toml` has changed in this pull-request
+  #         # ├── False
+  #         # │   └── Exit 0
+  #         # └── True
+  #         #     └── Check if lockfiles have changed in this pull-request
+  #         #         ├── True
+  #         #         │   └── Exit 0
+  #         #         └── False
+  #         #             └── Recompile lockfiles and check if they have to change
+  #         #                 ├── False
+  #         #                 │   └── Exit 0
+  #         #                 └── True
+  #         #                     └── Exit 1
 
-          changes=$(git diff --name-only HEAD^1 HEAD)
+  #         changes=$(git diff --name-only HEAD^1 HEAD)
 
-          if
-            (echo "${changes}" | grep -qE "skore/pyproject.toml") &&
-            (echo "${changes}" | (! grep -qE "ci/requirements/skore/.*/test-requirements.txt"))
-          then
-              curl -LsSf https://astral.sh/uv/0.6.16/install.sh | sh
-              bash ci/pip-compile.sh skore
+  #         if
+  #           (echo "${changes}" | grep -qE "skore/pyproject.toml") &&
+  #           (echo "${changes}" | (! grep -qE "ci/requirements/skore/.*/test-requirements.txt"))
+  #         then
+  #             curl -LsSf https://astral.sh/uv/0.6.16/install.sh | sh
+  #             bash ci/pip-compile.sh skore
 
-              if (git diff --name-only | grep -qE "ci/requirements/skore/.*/test-requirements.txt"); then
-                  echo '::error title=skore-lockfiles::Lockfiles obsolete, please execute `$ bash ci/pip-compile.sh skore`'
-                  exit 1
-             fi
-          fi
+  #             if (git diff --name-only | grep -qE "ci/requirements/skore/.*/test-requirements.txt"); then
+  #                 echo '::error title=skore-lockfiles::Lockfiles obsolete, please execute `$ bash ci/pip-compile.sh skore`'
+  #                 exit 1
+  #            fi
+  #         fi
 
   skore-test:
-    needs: [skore-changes]
-    if: ${{ (github.event_name == 'push') || (needs.skore-changes.outputs.changes == 'true') }}
+    # needs: [skore-changes]
+    # if: ${{ (github.event_name == 'push') || (needs.skore-changes.outputs.changes == 'true') }}
     strategy:
       fail-fast: false
       matrix:
-        os: ["ubuntu-latest", "windows-latest"]
-        python: ["3.9", "3.10", "3.11", "3.12"]
+        os: ["ubuntu-latest"]
+        python: ["3.12"]
         scikit-learn: ["1.6"]
         include:
-          - os: "ubuntu-latest"
-            python: "3.12"
-            scikit-learn: "1.4"
-          - os: "ubuntu-latest"
-            python: "3.12"
-            scikit-learn: "1.5"
           - os: "ubuntu-latest"
             python: "3.12"
             scikit-learn: "1.6"
@@ -185,7 +179,7 @@ jobs:
         working-directory: skore/
         run: |
           mkdir coverage
-          python -m pytest -n auto src/ tests/ --junitxml=coverage/coverage.xml --cov-config=pyproject.toml --cov | tee coverage/coverage.txt
+          python -m pytest -n auto src/ tests/ --junitxml=coverage/pytest.xml --cov-config=pyproject.toml --cov-report xml:coverage/pytest-coverage.xml --cov
 
       - name: Upload coverage reports
         if: ${{ matrix.coverage && (github.event_name == 'pull_request') }}
@@ -196,8 +190,8 @@ jobs:
 
   skore:
     needs:
-      - skore-changes
-      - skore-lockfiles
+      # - skore-changes
+      # - skore-lockfiles
       - skore-test
     if: ${{ always() }}
     runs-on: Ubuntu-latest
