Rename all `remote` references to `hub`

diff --git a/.github/workflows/skore-hub-project.yml b/.github/workflows/skore-hub-project.yml
--- a/.github/workflows/skore-hub-project.yml
+++ b/.github/workflows/skore-hub-project.yml
@@ -1,4 +1,4 @@
-name: skore-remote-project
+name: skore-hub-project
 
 on:
   pull_request:
@@ -19,10 +19,10 @@ defaults:
     shell: "bash"
 
 jobs:
-  skore-remote-project-changes:
+  skore-hub-project-changes:
     runs-on: ubuntu-latest
     outputs:
-      changes: ${{ steps.filter.outputs.skore-remote-project }}
+      changes: ${{ steps.filter.outputs.skore-hub-project }}
     permissions:
       pull-requests: read
     steps:
@@ -34,15 +34,15 @@ jobs:
         id: filter
         with:
           filters: |
-            skore-remote-project:
-              - '.github/workflows/skore-remote-project.yml'
-              - 'ci/requirements/skore-remote-project/**'
-              - 'skore-remote-project/**'
+            skore-hub-project:
+              - '.github/workflows/skore-hub-project.yml'
+              - 'ci/requirements/skore-hub-project/**'
+              - 'skore-hub-project/**'
 
-  skore-remote-project-lockfiles:
+  skore-hub-project-lockfiles:
     runs-on: "ubuntu-latest"
-    needs: [skore-remote-project-changes]
-    if: ${{ (contains(fromJSON('["pull_request", "merge_group"]'), github.event_name)) && (needs.skore-remote-project-changes.outputs.changes == 'true') }}
+    needs: [skore-hub-project-changes]
+    if: ${{ (contains(fromJSON('["pull_request", "merge_group"]'), github.event_name)) && (needs.skore-hub-project-changes.outputs.changes == 'true') }}
     permissions:
       contents: read
     steps:
@@ -72,21 +72,21 @@ jobs:
           changes=$(git diff --name-only HEAD^1 HEAD)
 
           if
-            (echo "${changes}" | grep -qE "skore-remote-project/pyproject.toml") &&
-            (echo "${changes}" | (! grep -qE "ci/requirements/skore-remote-project/.*/test-requirements.txt"))
+            (echo "${changes}" | grep -qE "skore-hub-project/pyproject.toml") &&
+            (echo "${changes}" | (! grep -qE "ci/requirements/skore-hub-project/.*/test-requirements.txt"))
           then
               curl -LsSf https://astral.sh/uv/0.6.16/install.sh | sh
-              bash ci/pip-compile.sh skore-remote-project
+              bash ci/pip-compile.sh skore-hub-project
 
-              if (git diff --name-only | grep -qE "ci/requirements/skore-remote-project/.*/test-requirements.txt"); then
-                  echo '::error title=skore-remote-project-lockfiles::Lockfiles obsolete, please execute `$ bash ci/pip-compile.sh skore-remote-project`'
+              if (git diff --name-only | grep -qE "ci/requirements/skore-hub-project/.*/test-requirements.txt"); then
+                  echo '::error title=skore-hub-project-lockfiles::Lockfiles obsolete, please execute `$ bash ci/pip-compile.sh skore-hub-project`'
                   exit 1
              fi
           fi
 
-  skore-remote-project-test:
-    needs: [skore-remote-project-changes]
-    if: ${{ (github.event_name == 'push') || (needs.skore-remote-project-changes.outputs.changes == 'true') }}
+  skore-hub-project-test:
+    needs: [skore-hub-project-changes]
+    if: ${{ (github.event_name == 'push') || (needs.skore-hub-project-changes.outputs.changes == 'true') }}
     strategy:
       fail-fast: false
       matrix:
@@ -123,15 +123,15 @@ jobs:
         uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
         id: cache-python-venv
         with:
-          path: 'skore-remote-project/venv'
+          path: 'skore-hub-project/venv'
           key: >-
             python-venv
             -${{ matrix.os }}
             -${{ steps.setup-python.outputs.python-version }}
-            -${{ hashFiles(format('ci/requirements/skore-remote-project/python-{0}/scikit-learn-{1}/test-requirements.txt', matrix.python, matrix.scikit-learn)) }}
+            -${{ hashFiles(format('ci/requirements/skore-hub-project/python-{0}/scikit-learn-{1}/test-requirements.txt', matrix.python, matrix.scikit-learn)) }}
 
       - name: Setup python-venv
-        working-directory: "skore-remote-project/"
+        working-directory: "skore-hub-project/"
         run: |
           set -eu
 
@@ -140,15 +140,15 @@ jobs:
 
           # Activate venv for each step depending on the OS
           if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
-              echo "${GITHUB_WORKSPACE}/skore-remote-project/venv/bin" >> ${GITHUB_PATH}
-              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}/skore-remote-project/venv" >> ${GITHUB_ENV}
+              echo "${GITHUB_WORKSPACE}/skore-hub-project/venv/bin" >> ${GITHUB_PATH}
+              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}/skore-hub-project/venv" >> ${GITHUB_ENV}
           else
-              echo "${GITHUB_WORKSPACE}\\skore-remote-project\\venv\\Scripts" >> ${GITHUB_PATH}
-              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}\\skore-remote-project\\venv" >> ${GITHUB_ENV}
+              echo "${GITHUB_WORKSPACE}\\skore-hub-project\\venv\\Scripts" >> ${GITHUB_PATH}
+              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}\\skore-hub-project\\venv" >> ${GITHUB_ENV}
           fi
 
       - name: Install dependencies in python-venv
-        working-directory: ${{ format('ci/requirements/skore-remote-project/python-{0}/scikit-learn-{1}', matrix.python, matrix.scikit-learn) }}
+        working-directory: ${{ format('ci/requirements/skore-hub-project/python-{0}/scikit-learn-{1}', matrix.python, matrix.scikit-learn) }}
         if: steps.cache-python-venv.outputs.cache-hit != 'true'
         run: |
           python -m pip install --upgrade pip build
@@ -158,27 +158,27 @@ jobs:
         uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
         if: steps.cache-python-venv.outputs.cache-hit != 'true'
         with:
-          path: 'skore-remote-project/venv'
+          path: 'skore-hub-project/venv'
           key: ${{ steps.cache-python-venv.outputs.cache-primary-key }}
 
       - name: Build
-        working-directory: skore-remote-project/
+        working-directory: skore-hub-project/
         run: python -m build
 
       - name: Install
-        working-directory: skore-remote-project/dist/
+        working-directory: skore-hub-project/dist/
         run: wheel=(*.whl); python -m pip install --force-reinstall --no-deps "${wheel}"
 
       - name: Test without coverage
         if: ${{ ! matrix.coverage }}
         timeout-minutes: 10
-        working-directory: skore-remote-project/
+        working-directory: skore-hub-project/
         run: python -m pytest -n auto src/ tests/ --no-cov
 
       - name: Test with coverage
         if: ${{ matrix.coverage }}
         timeout-minutes: 10
-        working-directory: skore-remote-project/
+        working-directory: skore-hub-project/
         run: |
           mkdir coverage
           python -m pytest -n auto src/ tests/ --junitxml=coverage/pytest.xml --cov-config=pyproject.toml --cov-report=xml:coverage/pytest-coverage.xml --cov
@@ -187,14 +187,14 @@ jobs:
         if: ${{ matrix.coverage && (github.event_name == 'pull_request') }}
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
         with:
-          name: skore-remote-project-coverage
-          path: skore-remote-project/coverage/
+          name: skore-hub-project-coverage
+          path: skore-hub-project/coverage/
 
-  skore-remote-project:
+  skore-hub-project:
     needs:
-      - skore-remote-project-changes
-      - skore-remote-project-lockfiles
-      - skore-remote-project-test
+      - skore-hub-project-changes
+      - skore-hub-project-lockfiles
+      - skore-hub-project-test
     if: ${{ always() }}
     runs-on: Ubuntu-latest
     steps:
