ci: Add workflow to lint/test `skore-remote-project` (#1598)
Some changes to prepare for the arrival of the new package
`skore-remote-project`:

- Rename the `skore` workflow from `backend` to `skore`,
- Factorize `pr-display-backend-coverage` to be usable by both `skore`
and `skore-remote-project`,
- Add the structure of the package `skore-remote-project`,
- Add the `skore-remote-project` workflow.

diff --git a/.github/workflows/skore-remote-project.yml b/.github/workflows/skore-remote-project.yml
--- a/.github/workflows/skore-remote-project.yml
+++ b/.github/workflows/skore-remote-project.yml
@@ -1,4 +1,4 @@
-name: backend
+name: skore-remote-project
 
 on:
   pull_request:
@@ -19,10 +19,10 @@ defaults:
     shell: "bash"
 
 jobs:
-  backend-changes:
+  skore-remote-project-changes:
     runs-on: ubuntu-latest
     outputs:
-      changes: ${{ steps.filter.outputs.backend }}
+      changes: ${{ steps.filter.outputs.skore-remote-project }}
     permissions:
       pull-requests: read
     steps:
@@ -34,14 +34,15 @@ jobs:
         id: filter
         with:
           filters: |
-            backend:
-              - '.github/workflows/backend.yml'
-              - 'skore/**'
+            skore-remote-project:
+              - '.github/workflows/skore-remote-project.yml'
+              - 'ci/requirements/skore-remote-project/**'
+              - 'skore-remote-project/**'
 
-  backend-lint:
+  skore-remote-project-lint:
     runs-on: "ubuntu-latest"
-    needs: [backend-changes]
-    if: ${{ (github.event_name == 'push') || (needs.backend-changes.outputs.changes == 'true') }}
+    needs: [skore-remote-project-changes]
+    if: ${{ (github.event_name == 'push') || (needs.skore-remote-project-changes.outputs.changes == 'true') }}
     permissions:
       contents: read
     steps:
@@ -58,15 +59,15 @@ jobs:
         run: python -m pip install --upgrade pip pre-commit
 
       - name: Lint
-        working-directory: skore/
+        working-directory: skore-remote-project/
         run: |
           pre-commit run --all-files ruff
           pre-commit run --all-files mypy
 
-  backend-lockfiles:
+  skore-remote-project-lockfiles:
     runs-on: "ubuntu-latest"
-    needs: [backend-changes]
-    if: ${{ (contains(fromJSON('["pull_request", "merge_group"]'), github.event_name)) && (needs.backend-changes.outputs.changes == 'true') }}
+    needs: [skore-remote-project-changes]
+    if: ${{ (contains(fromJSON('["pull_request", "merge_group"]'), github.event_name)) && (needs.skore-remote-project-changes.outputs.changes == 'true') }}
     permissions:
       contents: read
     steps:
@@ -96,21 +97,21 @@ jobs:
           changes=$(git diff --name-only HEAD^1 HEAD)
 
           if
-            (echo "${changes}" | grep -qE "skore/pyproject.toml") &&
-            (echo "${changes}" | (! grep -qE "ci/requirements/skore/.*/test-requirements.txt"))
+            (echo "${changes}" | grep -qE "skore-remote-project/pyproject.toml") &&
+            (echo "${changes}" | (! grep -qE "ci/requirements/skore-remote-project/.*/test-requirements.txt"))
           then
               curl -LsSf https://astral.sh/uv/0.6.16/install.sh | sh
-              bash ci/pip-compile.sh
+              bash ci/pip-compile.sh skore-remote-project
 
-              if (git diff --name-only | grep -qE "ci/requirements/skore/.*/test-requirements.txt"); then
-                  echo '::error title=backend-lockfiles::Lockfiles obsolete, please execute `$ bash ci/pip-compile.sh skore`'
+              if (git diff --name-only | grep -qE "ci/requirements/skore-remote-project/.*/test-requirements.txt"); then
+                  echo '::error title=skore-remote-project-lockfiles::Lockfiles obsolete, please execute `$ bash ci/pip-compile.sh skore-remote-project`'
                   exit 1
              fi
           fi
 
-  backend-test:
-    needs: [backend-changes]
-    if: ${{ (github.event_name == 'push') || (needs.backend-changes.outputs.changes == 'true') }}
+  skore-remote-project-test:
+    needs: [skore-remote-project-changes]
+    if: ${{ (github.event_name == 'push') || (needs.skore-remote-project-changes.outputs.changes == 'true') }}
     strategy:
       fail-fast: false
       matrix:
@@ -147,15 +148,15 @@ jobs:
         uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
         id: cache-python-venv
         with:
-          path: 'skore/venv'
+          path: 'skore-remote-project/venv'
           key: >-
             python-venv
             -${{ matrix.os }}
             -${{ steps.setup-python.outputs.python-version }}
-            -${{ hashFiles(format('ci/requirements/skore/python-{0}/scikit-learn-{1}/test-requirements.txt', matrix.python, matrix.scikit-learn)) }}
+            -${{ hashFiles(format('ci/requirements/skore-remote-project/python-{0}/scikit-learn-{1}/test-requirements.txt', matrix.python, matrix.scikit-learn)) }}
 
       - name: Setup python-venv
-        working-directory: "skore/"
+        working-directory: "skore-remote-project/"
         run: |
           set -eu
 
@@ -164,15 +165,15 @@ jobs:
 
           # Activate venv for each step depending on the OS
           if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
-              echo "${GITHUB_WORKSPACE}/skore/venv/bin" >> ${GITHUB_PATH}
-              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}/skore/venv" >> ${GITHUB_ENV}
+              echo "${GITHUB_WORKSPACE}/skore-remote-project/venv/bin" >> ${GITHUB_PATH}
+              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}/skore-remote-project/venv" >> ${GITHUB_ENV}
           else
-              echo "${GITHUB_WORKSPACE}\\skore\\venv\\Scripts" >> ${GITHUB_PATH}
-              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}\\skore\\venv" >> ${GITHUB_ENV}
+              echo "${GITHUB_WORKSPACE}\\skore-remote-project\\venv\\Scripts" >> ${GITHUB_PATH}
+              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}\\skore-remote-project\\venv" >> ${GITHUB_ENV}
           fi
 
       - name: Install dependencies in python-venv
-        working-directory: ${{ format('ci/requirements/skore/python-{0}/scikit-learn-{1}', matrix.python, matrix.scikit-learn) }}
+        working-directory: ${{ format('ci/requirements/skore-remote-project/python-{0}/scikit-learn-{1}', matrix.python, matrix.scikit-learn) }}
         if: steps.cache-python-venv.outputs.cache-hit != 'true'
         run: |
           python -m pip install --upgrade pip build
@@ -182,31 +183,27 @@ jobs:
         uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
         if: steps.cache-python-venv.outputs.cache-hit != 'true'
         with:
-          path: 'skore/venv'
+          path: 'skore-remote-project/venv'
           key: ${{ steps.cache-python-venv.outputs.cache-primary-key }}
 
       - name: Build
-        working-directory: skore/
+        working-directory: skore-remote-project/
         run: python -m build
 
       - name: Install
-        working-directory: skore/dist/
+        working-directory: skore-remote-project/dist/
         run: wheel=(*.whl); python -m pip install --force-reinstall --no-deps "${wheel}"
-
-      - name: Show dependencies versions
-        working-directory: skore/
-        run: python -c 'import skore; skore.show_versions()'
 
       - name: Test without coverage
         if: ${{ ! matrix.coverage }}
         timeout-minutes: 10
-        working-directory: skore/
+        working-directory: skore-remote-project/
         run: python -m pytest -n auto src/ tests/ --no-cov
 
       - name: Test with coverage
         if: ${{ matrix.coverage }}
         timeout-minutes: 10
-        working-directory: skore/
+        working-directory: skore-remote-project/
         run: |
           mkdir coverage
           python -m pytest -n auto src/ tests/ --junitxml=coverage/coverage.xml --cov-config=pyproject.toml --cov | tee coverage/coverage.txt
@@ -215,15 +212,15 @@ jobs:
         if: ${{ matrix.coverage && (github.event_name == 'pull_request') }}
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
         with:
-          name: backend-coverage
-          path: skore/coverage/
+          name: skore-remote-project-coverage
+          path: skore-remote-project/coverage/
 
-  backend:
+  skore-remote-project:
     needs:
-      - backend-changes
-      - backend-lint
-      - backend-lockfiles
-      - backend-test
+      - skore-remote-project-changes
+      - skore-remote-project-lint
+      - skore-remote-project-lockfiles
+      - skore-remote-project-test
     if: ${{ always() }}
     runs-on: Ubuntu-latest
     steps:
