ci: Cache python-venv in sphinx workflow

diff --git a/.github/workflows/sphinx.yml b/.github/workflows/sphinx.yml
--- a/.github/workflows/sphinx.yml
+++ b/.github/workflows/sphinx.yml
@@ -60,6 +60,15 @@ concurrency:
 
 permissions: {}
 
+defaults:
+  run:
+    shell: bash
+
+env:
+  PYTHON: '3.13'
+  SCIKIT_LEARN: '1.8'
+  LOCKFILE: 'ci/requirements/skore/python-3.13/scikit-learn-1.8/sphinx-requirements.txt'
+
 jobs:
   sphinx-changes:
     runs-on: ubuntu-latest
@@ -84,6 +93,51 @@ jobs:
               - 'sphinx/**'
               - 'skore/**'
 
+  sphinx-lockfiles:
+    runs-on: ubuntu-latest
+    needs: [sphinx-changes]
+    if: ${{ (contains(fromJSON('["pull_request", "merge_group"]'), github.event_name)) && (needs.sphinx-changes.outputs.changes == 'true') }}
+    permissions:
+      contents: read
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          fetch-depth: 2
+
+      - name: Check lockfiles are not obsolete
+        run: |
+          set -eu
+
+          # Check if `pyproject.toml` has changed in this pull-request
+          # ├── False
+          # │   └── Exit 0
+          # └── True
+          #     └── Check if lockfiles have changed in this pull-request
+          #         ├── True
+          #         │   └── Exit 0
+          #         └── False
+          #             └── Recompile lockfiles and check if they have to change
+          #                 ├── False
+          #                 │   └── Exit 0
+          #                 └── True
+          #                     └── Exit 1
+
+          changes=$(git diff --name-only HEAD^1 HEAD)
+
+          if
+            (echo "${changes}" | grep -qE "skore/pyproject.toml") &&
+            (echo "${changes}" | (! grep -qE "${LOCKFILE}"))
+          then
+              curl -LsSf https://astral.sh/uv/0.6.16/install.sh | sh
+              bash ci/pip-compile.sh --sphinx-requirements
+
+              if (git diff --name-only | grep -qE "${LOCKFILE}"); then
+                  echo '::error title=skore-sphinx-lockfiles::Lockfiles obsolete, please execute `$ bash ci/pip-compile.sh --sphinx-requirements`'
+                  exit 1
+             fi
+          fi
+
   sphinx-version:
     runs-on: ubuntu-latest
     needs: [sphinx-changes]
@@ -92,8 +146,7 @@ jobs:
       SPHINX_VERSION: ${{ steps.sphinx-version.outputs.SPHINX_VERSION }}
       SPHINX_RELEASE: ${{ steps.sphinx-version.outputs.SPHINX_RELEASE }}
     steps:
-      - shell: bash
-        id: sphinx-version
+      - id: sphinx-version
         run: |
           set -u
 
@@ -117,20 +170,70 @@ jobs:
     permissions:
       contents: read
     steps:
-      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+      - name: Checkout code
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
         with:
           lfs: 'true'
-      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
+
+      - name: Setup Python
+        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
+        id: setup-python
         with:
-          python-version: '3.13'
-          cache: 'pip'
-      - uses: ./.github/actions/sphinx/build
+          python-version: ${{ env.PYTHON }}
+          check-latest: True
+          cache: pip
+
+      - name: Restore python-venv
+        uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
+        id: cache-python-venv
+        with:
+          path: skore/venv
+          key: >-
+            python-venv
+            -ubuntu-latest
+            -${{ steps.setup-python.outputs.python-version }}
+            -${{ hashFiles(env.LOCKFILE) }}
+
+      - name: Setup python-venv
+        working-directory: skore
+        run: |
+          set -eu
+
+          # Ensure venv is created
+          python -m venv venv
+
+          # Activate venv for each step
+          echo "${GITHUB_WORKSPACE}/skore/venv/bin" >> ${GITHUB_PATH}
+          echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}/skore/venv" >> ${GITHUB_ENV}
+
+      - name: Install dependencies in python-venv
+        if: steps.cache-python-venv.outputs.cache-hit != 'true'
+        run: |
+          set -eu
+          python -m pip install --upgrade pip build
+          python -m pip install --requirement "${LOCKFILE}"
+
+      - name: Save python-venv
+        uses: actions/cache/save@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
+        if: steps.cache-python-venv.outputs.cache-hit != 'true'
+        with:
+          path: skore/venv
+          key: ${{ steps.cache-python-venv.outputs.cache-primary-key }}
+
+      - name: Install
+        working-directory: skore
+        run: python -m pip install --force-reinstall --no-deps .
+
+      - name: Build documentation
+        working-directory: sphinx
         timeout-minutes: 60
-        with:
+        run: make html
+        env:
           SPHINX_VERSION: ${{ needs.sphinx-version.outputs.SPHINX_VERSION }}
           SPHINX_RELEASE: ${{ needs.sphinx-version.outputs.SPHINX_RELEASE }}
           SPHINX_DOMAIN: ${{ vars.DOCUMENTATION_DOMAIN }}
-      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
+      - name: Upload documentation
+        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
         with:
           name: sphinx-html-artifact
           path: sphinx/build/html/
@@ -248,8 +351,7 @@ jobs:
       - sphinx-deploy-html
       - sphinx-deploy-root-files
     steps:
-      - shell: bash
-        run: |
+      - run: |
           curl --fail-with-body \
           -X POST \
           --url "https://api.bunny.net/pullzone/${PULLZONE}/purgeCache" \
@@ -270,6 +372,7 @@ jobs:
   sphinx:
     needs:
       - sphinx-changes
+      - sphinx-lockfiles
       - sphinx-version
       - sphinx-build
       - sphinx-deploy-html
@@ -278,6 +381,5 @@ jobs:
     if: ${{ always() }}
     runs-on: Ubuntu-latest
     steps:
-      - shell: bash
-        run: |
+      - run: |
           [[  ${{ contains(needs.*.result, 'failure') }} = false ]]
